/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
<<<<<<< HEAD
export type { ERC20R } from "./ERC20R";
export type { ETHr } from "./ETHr";
=======
import type * as mock from "./mock";
export type { mock };
export type { NFortress } from "./NFortress";
export type { NFortress_v1 } from "./NFortress_v1";
>>>>>>> 5b80d6791d95baa478f51ab21b585fb212a5824d
